name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install LibreOffice
        run: sudo apt-get install -y libreoffice

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make dpkg-dev pandoc

      - name: Build the Package
        run: make

      - name: Install the Package
        run: sudo make install

      - name: Generate Sample PDFs
        run: |
          chmod +x generate_sample_pdfs.sh
          ./generate_sample_pdfs.sh test_root_folder

      - name: List Contents of test_root_folder
        run: ls -la test_root_folder

      - name: Run the Organizer Script
        run: organize_pdfs --root test_root_folder --report

      - name: Display Analysis Report
        run: cat test_root_folder/analysis_report.txt

      - name: Uninstall the Package
        run: sudo make uninstall

      - name: Clean Up
        run: make clean
